name: Tests unitaire de l'app
on:
  push:
    branches:
      - master
env:
  APP_VERSION: "1.0.0"
jobs: 
  Tests-app: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
      - run: npm install
      - run: npm start
      - run: npm test
      - run: npm run cover
      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: /home/runner/work/quick-example-of-testing-in-nodejs/quick-example-of-testing-in-nodejs/reports/
  Build-app:
    needs: Tests-app
    runs-on: ubuntu-latest
    steps:
      - name: recup du repository
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/setup-qemu-action@v1
      - name: Installation de docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login au docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
      - name: Build & push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/testunit:${{APP_VERSION}}