name: mon premier test # On donne un titre à notre Workflow
# On indique a github quand le déclencher
# Est ce qu'on le déclenche au push, pull request, merge, push sur la branche ""
on: push
# On déclare des processus de travail
jobs:
# On donne un nom à nos jobs
  Tests:
    runs-on: ubuntu-latest
  # On declare les tâches que notre processus va executer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
      - name: "install npm"
        run: npm install 
      - name: "start test plus"
        run: npm run cover
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            ./reports/coverage
            ./reports/coverage/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./reports/coveragecode-coverage.html
  